### ISSUE TITLE
Support javax.validation.constraints annotation

### ISSUE THREAD

**Issue by akutschera** [Nylle/JavaFixture#61]
Assume we have the following class
```
class Foo {
  @Size(max = 6)
  String value;
}
```

I want the following test to be green
```
        var sut = new Fixture().create(Foo.class);

        assertThat(sut.value.size()).isLessThan(7);
```

Use case:
We have objects that are a fixed length string (e.g. some internal key) and we want JavaFixture to create only valid objects.

Advantage:
When our business logic requires a certain constraint (e.g. ```@Email```) and the annotation is not present, some tests may fail and thus force us to add the annotation and improve maintainability (currently all tests that require a valid email address would fail because we only create a random string).
It would make it possible to create objects that can be persisted in a test database where we have a length limit for strings.

Disadvantage:
It would be possible to configure JavaFixture in a way that a valid object can never be created (e.g. numbers with max < 0 and JavaFixture.usePositiveNumbersOnly(true)). Since there are annotations to specify that a number should be positive, the JavaFixture configuration would then only make sense for (legacy?) systems where there is some kind of hidden logic in the number sign.

Maybe it could be a good idea to start with just string size annotations because this will have a big impact on JPA tests.

**Comment by Nylle** [comment]
I like that! Let's start with string-size, since magic strings are most common source of unexpected application behaviour.

As for conflicts between number sizes vs `usePositiveNumbersOnly` we might even go as far as throwing an exception if we detect that.

**Comment by akutschera** [comment]
Turns out that this only works if the project that uses JavaFixture does **not** have a dependendy to ```jakarta.validation:jakarta.validation-api:2.x``` because that will override JavaFixture's version 3.x and then JavaFixture complains with ```java.lang.NoClassDefFoundError: jakarta/validation/constraints/Size```.
It's probably a better idea to just support javax.validation constraints and move to jakarta.validation in a major update (possibly with a move to Java 17).

So instead of creating a bug that the last PR did not solve this issue, I re-opened it.

**Comment by jk-idealo** [comment]
Next annotation should be `@Column(length = 50, nullable = false)` in `javax.persistence`?

**Comment by jk-idealo** [comment]
Investigate support for numerical limits like `@Column(columnDefinition = "int(11)")` even though a `string` defining the type seems pretty weird. 
- Is that even valid? 
- What DDL would it create? 
- Are there alternatives?
[Further reading.](https://stackoverflow.com/questions/46075191/restrict-length-of-number-column-using-jpa)

**Comment by akutschera** [comment]
In the jakarta.persistence-spec 3.1.0 (see [here](https://github.com/eclipse-ee4j/jpa-api/tree/3.1-3.1.0-RELEASE/spec)), It says in 11.2.2
```
Applications that are sensitive
to the exact database mappings that are generated should use the columnDefinition element of the
Column annotation or include DDL files that specify how the database schema is to be generated.
```
To me that sounds that if you use this attribute you either need something very specific to your database or you may have a portability bug in your entities. I don't think that JavaFixture should support any database specific annotation attributes for generating test entities and if the generated entity breaks your test then maybe you found something in your design that you should fix.

**Comment by Nylle** [comment]
I'm pretty sure, I found design-flaw, I'm just not quite sure how to resolve it. Would it be a better approach to use
```java
@Column(precision = 2, scale = 0)
private BigDecimal weightedScore;
```
instead?

**Comment by akutschera** [comment]
That would depend on your use case.
```java
@Column(columnDefinition = "int(11)")
private BigDecimal weightedScore;
```
will allow you to anything up to Integer.MAX_VALUE (2_147_483_647) while
```java
@Column(precision = 11, scale = 0)
private BigDecimal weightedScore;
```
will allow you to store any 11-digit number (which is one digit more than Integer.MAX_VALUE) and a lot less than Long.MAX_VALUE.

**Comment by jk-idealo** [comment]
I think, I messed up the examples, but looking at what you just wrote, it makes totally sense.

This is what I found:
```java
@Column(columnDefinition = "int(11)")
private Long weightedScore;
```
It uses a `long` that is simply 1 digit more than an `int`. So one could get completely rid of the `columnDefinition` and either use `Integer` (10 digits) or got for unrestricted `Long` I guess.

**Comment by akutschera** [comment]
Actually, this column definition is not valid everywhere. It works on H2,  MySQL and Mariadb. There the "(11)" is the display width of the column which has nothing to do with how many digits you can store. If you try to execute a 
```sql
CREATE TABLE foo (val int(11));
```
on e.g. a postgres database, the server won't let you.

**Comment by jk-idealo** [comment]
Related to [#82](https://github.com/Nylle/JavaFixture/issues/82).
