### ISSUE TITLE
Inconsistent behaviour for `.without()` with inner classes

### ISSUE THREAD

**Issue by jk-idealo** [Nylle/JavaFixture#97]
When using `fixture().build(MyClass.class).without("myField").create()`, I'd expect the field "myField" to be always `null`.

This is the case for any class, primitive, and of course collections, and also overrides initialisation as the following (green) test confirms:

```java
class FixtureTest {
    class TestClass {
        private List<String> collection = List.of(); // initialised
    }

    @Test
    void weAreFine() {

        var actual = fixture()
                .build(TestClass.class)
                .without("collection").create();

        assertThat(actual.collection).isNull();
    }
}
```

However, when my `TestClass` is defined within an _interface_, things get odd, because the field is suddenly initialised:

```java
class FixtureTest {

    interface OuterInterface {
        class TestClass {
            private List<String> collection = List.of();
        }
    }

    class OuterClass {
        class TestClass {
            private List<String> collection = List.of();
        }
    }

    @Test
    void huh() {
        // works as expected:
        var inInterface = fixture().build(OuterClass.TestClass.class).without("collection").create();
        assertThat(inInterface.collection).isNull();

        // fails:
        var inClass = fixture().build(OuterInterface.TestClass.class).without("collection").create();
        assertThat(inClass.collection).isNull();
    }
}
```

Unless there is a good explanation, I'd expect `.without()` to behave consistently no matter whether my class is defined within an interface or class.

**Comment by akutschera** [comment]
I agree that the behaviour of `.without()` should be consistent.
I believe we implemented that in #16. There we changed the behaviour of JavaFixture to **not touch** any fields in the "without"-List. That means that when you instantiate a field in your class like you did above, it stays instantiated, because we don't overwrite it.
I think that is proper behaviour because as a user of a fixtured object I want an object that I could have gotten via "normal" creation (constructor + a few setters or a factory method + a few setters/method calls etc.).
So the expected value of `collection` is an empty list. 

Which leads me to the `OuterClass.TestClass`. It is impossible to construct an instance of `OuterClass.TestClass` without an enclosing `OuterClass`, unless you do it via byte manipulation (in our case objenesis). Then you get an instance with no fields set and we ignore the collection so it won't be set.

So I think that actually the second test above constructs a correct object.
When you try to fixture an object that cannot be created without bytecode manipulation, I say the result is undefined. Please try to change my view.

I would like to know the actual use case for which you need an inner class that cannot exist by itself but needs to have certain attributes for a test. Maybe we can find a better way to solve that problem.

**Comment by jk-idealo** [comment]
I agree that it makes sense that initialised fields are not "nulled", in fact I was upset a few times that fixturing an object "overwrote" the initialisation so I had to use `with()` just to emulate production-behaviour. My gripe is that either way is not consistent.

What I don't quite understand is why the outer interface matters. A class alone and a class inside another class both get the initialised field "nulled", but not when the class is inside an interface. 

The use-case is that since recently we're keeping "dtos" and "entities" inside their respective components for "cleanliness" (we're trying out how it looks and whether we like that). That means a mongo-repository (which is an interface) contains its document-class and a REST-controller (which is a class) contains it's model-class. We initialise the collections to avoid constant null-checking, knowing that the collection can never be null if missing. When testing it caught my eye, that sometimes fixtured "nulled" the initialised field and sometimes it didn't.

**Comment by akutschera** [comment]
In the example you gave, while it's possible to create just a `new OuterInterface.TestClass()`, you cannot create a `new OuterClass.TestClass()`. The compiler won't let you. So we could let JavaFixture fail in this case (I honestly think that may be a good idea to avoid confusion).
However, in case you are using Java 17+ ,  making TestClass static will probably do what you want.
```
    class OuterClass {
         static class TestClass {
            private List<String> collection = List.of();
        }
    }
```

In addition to that maybe we could update the README. Here's a proposal:

JavaFixture simplifies using random objects for your tests.
We do this by constructing an object either with any public constructor or with a public factory method (JavaFixture will use random parameter values for this). When constructing with an empty constructor (e.g. `new MyObject()`), JavaFixture will then try to set the private fields of the object to random values.

**NB** When a new object cannot be created, JavaFixture will use byte manipulation to build an object. In that case the private fields may or may not be set (it's random, actually)

**Comment by jk-idealo** [comment]
Okay, so in order to be as precise as possible, I changed the test setup to mirror the production use-case more closely.

I have a class:
```java
public class OuterClass {
    public static class TestClass {
        private List<String> collection = List.of();

        public List<String> getCollection() {
            return collection;
        }
    }
}
```

...and I have an interface
```java
public interface OuterInterface {
    class TestClass {
        private List<String> collection = List.of();

        public List<String> getCollection() {
            return collection;
        }
    }
}
```

And I have a test:
```java
class FixtureTest {
    @Test
    void thisWorksNow() {

        var inInterface = fixture().build(OuterClass.TestClass.class).without("collection").create();
        assertThat(inInterface.getCollection()).isEmpty();

        var inClass = fixture().build(OuterInterface.TestClass.class).without("collection").create();
        assertThat(inClass.getCollection()).isEmpty();
    }
}
```

And you know what? It returns an empty list for both, the interface and the class. It behaves consistently now. I think I messed up when I inlined the outer-class inside the test and didn't put access-modifiers on it.

I wrote this ticket, because I expected `null`, but got an empty list. Now, as you explained, this is expected behaviour which I simply forgot. 

However, why I was able to produce another case where I got `null`from the interface I don't know. I'm not able to reproduce this behaviour, so I would recommend to close this ticket and open a new one once I run into the issue.

As for your README proposal, I like it!
