### ISSUE TITLE
Set all fields for type not working correctly

### ISSUE THREAD

**Issue by martinjunker** [Nylle/JavaFixture#98]
Since version 2.9.5 (2.9.5 is first broken version) the feature [Set all fields for type](https://github.com/Nylle/JavaFixture#set-all-fields-for-type) is not working correctly. 

`ISpecimenBuilder<Item> ITEM_BUILDER = Fixture.fixture().build(Item.class)
            .with(BigDecimal.class, BigDecimal.valueOf(10000));`

In `Item` is a deep nested property with BigDecimals and these are not set to my defined value but to a random one.

**Comment by akutschera** [comment]
Nice catch.
The current implementation only checks for predefined instances of certain types. Special types (that need special constructor parameters, such as BigInteger) were not among them.
The commit above should fix that.

**Comment by Nylle** [comment]
Fixed in version [2.9.9](https://github.com/Nylle/JavaFixture/releases/tag/2.9.9).

**Comment by martinjunker** [comment]
Thx, for fixing it!
